chore: PEx v2 input_descriptors schema/type requirement example update
decentralized-identity/waci-presentation-exchange pull request #132
Opened 2021-12-13 20:44 UTC by rolsonquadras

schema/type requirement example update based on DIF PEx v2

Reference - https://identity.foundation/presentation-exchange/#input-descriptor-object

2021-12-13 20:53 UTC, OR13 commented on spec/spec.md
> +                "@schema": [
is this supposed to be `@schema` ?

2021-12-13 20:53 UTC, OR13 commented on spec/spec.md
> +                        "schema":[
@rolsonquadras do this look right to you?

2021-12-13 20:55 UTC, OR13 approved these changes
I think this is correct, but pinging other folks for a review, since we changed this recently IIRC.

2021-12-13 21:00 UTC, rolsonquadras commented on spec/spec.md
> +                "@schema": [
my bad, fixed it now.

2021-12-13 21:12 UTC, OR13 requested changes
Suggest we remove the `schema` property, as its no longer required / supported in PE v2.

2021-12-13 21:12 UTC, bumblefudge commented
https://identity.foundation/presentation-exchange/#input-descriptor-object
^ The current draft that migrates `schema` to `fields`. See discussion on https://github.com/decentralized-identity/presentation-exchange/issues/256

2022-01-10 16:08 UTC, rolsonquadras commented
Thanks @OR13 @bumblefudge - Removed custom schema and added it as part of constraints (according to PEx v2)

2022-01-10 18:37 UTC, OR13 approved these changes

2022-01-10 21:15 UTC, brentzundel approved these changes

2022-01-10 21:22 UTC, rolsonquadras commented
@brentzundel @OR13 - fixed merge conflicts

2022-01-10 21:25 UTC, brentzundel commented
multiple positive reviews, feedback incorporated, merging

2022-01-10 21:25 UTC, merged