rendering v0.1 as a distinct snapshot?
decentralized-identity/waci-presentation-exchange pull request #133
Opened 2021-12-13 20:44 UTC by bumblefudge

I opened a separate PR because this might be superfluous given the "versions" script I found but couldn't understand, but I looked at [the way distinct versions are pulled out in the Pres Ex spec](https://github.com/decentralized-identity/presentation-exchange/blob/master/specs.json) and tried to replicate it here in case it would help with #131 ? (I preserved the web.archive version as well just in case)

2021-12-13 20:56 UTC, OR13 reviewed
@csuwildcat is this the recommended way to do this?

2021-12-13 21:17 UTC, OR13 requested changes
@bumblefudge please refer to the spec up documentation to justify this approach, I will approve when the spec up readme says what you have done here is recommended.

2021-12-13 21:19 UTC, csuwildcat approved these changes

2021-12-13 21:19 UTC, csuwildcat commented on spec/specs.json
> +      "output_path": "./build/v0.1",
Might want to do v0.1.0

2021-12-13 21:53 UTC, OR13 approved these changes

2021-12-13 21:58 UTC, brentzundel approved these changes

2022-01-10 21:10 UTC, brentzundel commented
multiple positive reviews.

2022-01-10 21:10 UTC, merged