Pres exchange context
decentralized-identity/waci-presentation-exchange pull request #73
Opened 2021-07-27 20:10 UTC by brentzundel

Adds language to the presentation exchange context and describes what is needed for the `format` property

2021-08-02 20:16 UTC, OR13 approved these changes

2021-08-02 20:22 UTC, OR13 commented on spec/spec.md
> +`BbsBlsSignatureProof2020` or `BbsBlsBoundSignatureProof2020`.
```suggestion
`BbsBlsSignature2020`, `JsonWebSignature2020`, or `Ed25519Signature2018`.
```

2021-08-02 20:23 UTC, OR13 commented on spec/spec.md
> +`BbsBlsSignatureProof2020` or `BbsBlsBoundSignatureProof2020`.
the VP does not need to be related to the `derivedCredential` that is in the `verifiableCredential` property of the VP.

2021-08-02 20:24 UTC, OR13 commented on spec/spec.md
> +        "proof_type": ["BbsBlsSignatureProof2020", "BbsBlsBoundSignatureProof2020"]
```suggestion
        "proof_type": ["BbsBlsSignature2020", "JsonWebSignature2020", "Ed25519Signature2018"]
```

2021-08-02 20:25 UTC, OR13 requested changes
I think we don't are the suite of the presentation.

We DO care that the credential type is `BbsBlsSignatureProof2020`.

2021-08-02 20:26 UTC, OR13 commented
There exist merge conflicts.

2021-08-02 21:20 UTC, brentzundel commented
@OR13 @TelegramSam merge conflicts resolved

2021-08-09 20:01 UTC, OR13 approved these changes

2021-08-09 20:07 UTC, merged